-- ── Migration: fba_removals missing columns ──
ALTER TABLE fba_removals ADD COLUMN IF NOT EXISTS order_source VARCHAR(255);
ALTER TABLE fba_removals ADD COLUMN IF NOT EXISTS order_type VARCHAR(50);
ALTER TABLE fba_removals ADD COLUMN IF NOT EXISTS last_updated TIMESTAMP;
ALTER TABLE fba_removals ADD COLUMN IF NOT EXISTS cancelled_qty INTEGER DEFAULT 0;
ALTER TABLE fba_removals ADD COLUMN IF NOT EXISTS disposed_qty INTEGER DEFAULT 0;
ALTER TABLE fba_removals ADD COLUMN IF NOT EXISTS in_process_qty INTEGER DEFAULT 0;
ALTER TABLE fba_removals ADD COLUMN IF NOT EXISTS removal_fee NUMERIC(10,2) DEFAULT 0;
ALTER TABLE fba_removals ADD COLUMN IF NOT EXISTS currency VARCHAR(10);

-- ── Migration: fba_summary missing columns ──
ALTER TABLE fba_summary ADD COLUMN IF NOT EXISTS in_transit INTEGER DEFAULT 0;
ALTER TABLE fba_summary ADD COLUMN IF NOT EXISTS vendor_returns INTEGER DEFAULT 0;
ALTER TABLE fba_summary ADD COLUMN IF NOT EXISTS found INTEGER DEFAULT 0;
ALTER TABLE fba_summary ADD COLUMN IF NOT EXISTS lost INTEGER DEFAULT 0;
ALTER TABLE fba_summary ADD COLUMN IF NOT EXISTS damaged INTEGER DEFAULT 0;
ALTER TABLE fba_summary ADD COLUMN IF NOT EXISTS disposed_qty INTEGER DEFAULT 0;
ALTER TABLE fba_summary ADD COLUMN IF NOT EXISTS other_events INTEGER DEFAULT 0;
ALTER TABLE fba_summary ADD COLUMN IF NOT EXISTS unknown_events INTEGER DEFAULT 0;
ALTER TABLE fba_summary ADD COLUMN IF NOT EXISTS location VARCHAR(50);
ALTER TABLE fba_summary ADD COLUMN IF NOT EXISTS store VARCHAR(100);

SELECT 'Migration complete!' as status;
